Add Profile Attribute APIs for both Android & iOS
sefidgaran/salesforce-marketing-cloud pull request #5
Opened 2022-10-19 12:51 UTC by ishangavidusha

## Set Profile  Attributes

You can use attributes to segment your audience and personalize your messages. Before you can use attributes, create them in your MobilePush account. Attributes may only be set or cleared by the SDK. See the [Reserved Words](https://salesforce-marketingcloud.github.io/MarketingCloudSDK-Android/sdk-implementation/device-contact-registration.html#reserved-words) section for a list of attribute keys that can’t be modified by the SDK or your application.

### New APIs
```dart
await SfmcPlugin().setProfileAttribute("key", "value");

await SfmcPlugin().clearProfileAttribute("key");
```

- Test passed on all platforms

2022-10-19 21:28 UTC, sefidgaran requested changes
Left a comment. thanks

2022-10-19 21:28 UTC, sefidgaran commented on src/ios/Classes/SwiftSfmcPlugin.swift
> +        SFMCSdk.identity.setProfileAttribute(key, "")
Please use the SDK clear attr func: 
<img width="388" alt="image" src="https://user-images.githubusercontent.com/22389242/196805312-ca83005b-9e62-4ca9-8186-e84dcab3a2c2.png">

2022-10-20 02:37 UTC, ishangavidusha commented on src/ios/Classes/SwiftSfmcPlugin.swift
> +        SFMCSdk.identity.setProfileAttribute(key, "")
Okay, Done.

2022-10-20 03:20 UTC, sefidgaran approved these changes

2022-10-20 03:21 UTC, merged